services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: